runtime: python39
entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /static
  static_dir: static
  http_headers:
    Cache-Control: "no-cache, no-store, must-revalidate"
    Pragma: "no-cache"
    Expires: "0"

- url: /.*
  script: auto